apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- files:
  - tls.key
  - tls.crt
  name: signer-ca
  namespace: signer-ca-system
  type: kubernetes.io/tls
resources:
- rbac.yaml
- ../default
patchesStrategicMerge:
- patch_add_signer_pki_files.yaml
images:
- name: controller
  newName: appviewx-istio/appviewx-signer/controller
  newTag: "1.0"
